# Generated by Django 5.1 on 2024-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evenement_is_approved_lieu_is_approved_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
